on: deployment
env:
  USE_DOCKER: 1
jobs:
  prepare:
    name: Prepare Gitian build environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare
      if: steps.base-cache.outputs.cache-hit != 'true'
      run: |
        for i in bionic xenial; do
            if ! docker image ls | grep -q "base-$i-amd64"; then
                vendor/gitian-builder/bin/make-base-vm --docker --suite "$i"
            fi
        done
  linux:
    name: Build and sign linux binaries
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Load Build Cache
      uses: actions/cache@v1
      with:
        path: vendor/gitian-builder/cache/bitshares-core-linux
        key: build-cache-linux
    - name: Build and Sign
      run: |
        export GNUPGHOME=`pwd`/.gpghome
        echo ${{ secrets.PGP_PASSPHRASE }} 1>&3 \
          | ./run-gitian -b -s BitShares-Gitian-Auto-Build-Signer \
                         -p "gpg --passphrase-fd 3" -O linux ${{ github.event.coreversion }} -j 1
    - name: Upload build artifacts
      uses: actions/upload-artifact@master
      with:
        name: Linux-Binaries
        path: vendor/gitian-builder/build/out
  mac:
    name: Build and sign mac binaries
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Load Build Cache
      uses: actions/cache@v1
      with:
        path: vendor/gitian-builder/cache/bitshares-core-osx
        key: build-cache-osx
    - name: Build and Sign
      run: |
        export GNUPGHOME=`pwd`/.gpghome
        echo ${{ secrets.PGP_PASSPHRASE }} 1>&3 \
          | ./run-gitian -b -s BitShares-Gitian-Auto-Build-Signer \
                         -p "gpg --passphrase-fd 3" -O linux ${{ github.event.coreversion }} -j 1
    - name: Upload build artifacts
      uses: actions/upload-artifact@master
      with:
        name: Mac Binaries
        path: vendor/gitian-builder/build/out
  windows:
    name: Build and sign windows binaries
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Load Build Cache
      uses: actions/cache@v1
      with:
        path: vendor/gitian-builder/cache/bitshares-core-win
        key: build-cache-win
    - name: Build and Sign
      run: |
        export GNUPGHOME=`pwd`/.gpghome
        echo ${{ secrets.PGP_PASSPHRASE }} 1>&3 \
          | ./run-gitian -b -s BitShares-Gitian-Auto-Build-Signer \
                         -p "gpg --passphrase-fd 3" -O linux ${{ github.event.coreversion }} -j 1
    - name: Upload build artifacts
      uses: actions/upload-artifact@master
      with:
        name: Windows Binaries
        path: vendor/gitian-builder/build/out
